package:
  - name: packetx
    version: v.1.2.x or latest
    location: ./localfolder / https://github.x/ChriKarb/paket3/blob/{version}
  - name: packetx
    version: v.1.2.x or latest
    location: ./localfolder / https://github.x/ChriKarb/paket3/blob/{version}
  
  
