# tasks/Makefile.actions


## Install
actions/install: actions/v1.5.1/install
	@echo "Install actions first packet"

## version
actions/version:

## exists
actions/exists:

## needs
actions/needs:

## install v1.5.1
actions/v1.5.1/install:
	@echo "Install action version v1.5.1 first packet"

